#
#  _____       _                _____  _             _
# |  __ \     | |              |  __ \| |           (_)
# | |  | | ___| |_   ___  _____| |__) | |_   _  __ _ _ _ __  ___
# | |  | |/ _ \ | | | \ \/ / _ \  ___/| | | | |/ _` | | '_ \/ __|
# | |__| |  __/ | |_| |>  <  __/ |    | | |_| | (_| | | | | \__ \
# |_____/ \___|_|\__,_/_/\_\___|_|    |_|\__,_|\__, |_|_| |_|___/
#                                               __/ |
#                                              |___/
#
# Author: FusionCoding
# Version: 1.0
# State: ALPHA
#
General:
 Prefix: "&bDeluxe&7Plugins \xbb &7"
